"""Add level_assigned column to quests table

Revision ID: 018af85afbfa
Revises: acad72b689a6
Create Date: 2025-07-27 19:59:53.867488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018af85afbfa'
down_revision: Union[str, Sequence[str], None] = 'acad72b689a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('level_assigned', sa.Integer(), nullable=False, server_default='0'))
    
    op.add_column('quests', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1'))) # '1' for True
    
    # ---- THIS IS THE CORRECTED LINE ----
    op.add_column('quests', sa.Column('is_completed', sa.Boolean(), nullable=False, server_default=sa.text('0'))) # '0' for False
    
    op.create_index(op.f('ix_quests_level_assigned'), 'quests', ['level_assigned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_quests_level_assigned'), table_name='quests')
    #op.drop_column('quests', 'is_completed')
    #op.drop_column('quests', 'is_active')
    #op.drop_column('quests', 'level_assigned')
    # ### end Alembic commands ###