"""Add is_active column to quests

Revision ID: 45a249276c1e
Revises: 018af85afbfa
Create Date: 2025-07-30 02:12:43.603389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a249276c1e'
down_revision: Union[str, Sequence[str], None] = '018af85afbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('quests', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_quests_level_assigned'), 'quests', ['level_assigned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quests_level_assigned'), table_name='quests')
    op.drop_column('quests', 'is_completed')
    op.drop_column('quests', 'is_active')
    # ### end Alembic commands ###
