"""Add user_id to QuestCompletion table

Revision ID: 9bb354123931
Revises: 916363098a84
Create Date: 2025-11-02 22:37:00.389427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb354123931'
down_revision: Union[str, Sequence[str], None] = '916363098a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Operations for 'quest_completions' table must use batch_alter_table for SQLite
    with op.batch_alter_table('quest_completions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True)) # Added nullable=True
        # Re-creating index that was auto-generated, but now within batch_op
        # If 'ix_quest_completions_quest_id' already existed and wasn't part of the 'new' model
        # it might not need to be recreated here. But if it was generated with this migration,
        # it should be handled consistently. Let's include it for now.
        batch_op.create_index(batch_op.f('ix_quest_completions_quest_id'), ['quest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_completions_user_id'), ['user_id'], unique=False)
        # Create foreign key with an explicit name using batch_op.f()
        batch_op.create_foreign_key(batch_op.f('fk_quest_completions_user_id_users'), 'users', ['user_id'], ['id'])

    # Dropping a column from 'quests' typically does not require batch mode in SQLite
    op.drop_column('quests', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add back the 'is_completed' column to 'quests'
    op.add_column('quests', sa.Column('is_completed', sa.BOOLEAN(), nullable=False))

    # Operations for 'quest_completions' table must use batch_alter_table for SQLite
    with op.batch_alter_table('quest_completions', schema=None) as batch_op:
        # Drop the foreign key using the consistent name
        batch_op.drop_constraint(batch_op.f('fk_quest_completions_user_id_users'), type_='foreignkey')
        # Drop the indexes
        batch_op.drop_index(batch_op.f('ix_quest_completions_user_id'))
        # Dropping the quest_id index if it was created by this upgrade.
        # If it was an existing index and not touched by the upgrade, this line might cause an error
        # but auto-generated downgrades usually try to reverse everything.
        batch_op.drop_index(batch_op.f('ix_quest_completions_quest_id'))
        # Drop the user_id column
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###