"""Fix missing columns in quests table

Revision ID: aabb9eb60b3b
Revises: 45a249276c1e
Create Date: 2025-07-30 02:34:08.354375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabb9eb60b3b'
down_revision: Union[str, Sequence[str], None] = '45a249276c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column(
        'quests',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')) # '1' for True
    )
    op.add_column(
        'quests',
        sa.Column('is_completed', sa.Boolean(), nullable=False, server_default=sa.text('0')) # '0' for False
    )
    op.create_index('idx_quests_level_assigned', 'quests', ['level_assigned'], unique=False)
    op.create_index(op.f('ix_quests_level_assigned'), 'quests', ['level_assigned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quests_level_assigned'), table_name='quests')
    op.drop_column('quests', 'is_completed')
    op.drop_column('quests', 'is_active')
    # ### end Alembic commands ###
